<?php

namespace App\Conversations;

use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Conversations\Conversation;
use App\User;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Outgoing\Question;

class ExistingUserConversation extends UserConversation
{

    protected $user;

    public function __construct(User $user) {
        $this->$user = $user;
    }

    public function showDetails() {
        $this->ask('What is your full name?', function(Answer $answer) {

            $this->fullName = $answer->getText();

            $this->say('Nice to meet you '.$this->fullName);
            $this->askContact();
        });
    }

    protected function storeUser() {
        parent::storeUser(); // TODO: Change the autogenerated stub
        $this->say('Perfect! Your new changes have been saved.');
    }

    // Start conversation
    public function run() {
        $this->showDetails();
    }
}
